### ISSUE TITLE
GitLab runners do not have `docker` tag

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/hgi-ansible#10]
The GitLab runners that are being setup for our projects don't have a `docker` tag. They have `docker-privileged` but this doesn't match.

**Comment by jrandall** [comment]
Oops - I see this is called `dockerers` now. This should be fixed here so that they are tagged with `docker` and `docker-privileged` (if they are also a docker privileged capable runner)

Can probably get rid of the code to tag them with arbitrary ansible groups/roles that have been applied. Now that we are using docker-machine, that won't matter anyway.

**Comment by colin-nolan** [comment]
`docker` tag now present.
